image: node:16

pipelines:
  default:
    - parallel:
      - step:
          name: Build
          caches:
            - node
          script:
            - yarn
            - yarn build
          artifacts:
            - build/**
  branches:
    master:
      - parallel:
        - step:
            name: Build
            caches:
              - node
            script:
              - yarn
              - yarn build
            artifacts:
              - build/**

        - step:
            name: Deploy to Production
            deployment: Production
            trigger: manual
            script:
              - yarn
              - yarn build
              # Sync your files to S3
              - pipe: atlassian/aws-s3-deploy:1.1.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: $AWS_S3_BUCKET_NAME
                  LOCAL_PATH: 'build'